### ISSUE TITLE
upload your cool frontend websites 

### ISSUE THREAD

**Issue by adyasha9** [adyasha9/hacktoberfest#1]
Please post original work

**Comment by padmaja-22** [comment]
Can i contribute?

**Comment by adyasha9** [comment]
yes go ahead

**Comment by padmaja-22** [comment]
I can add any of my frontend projects right

**Comment by adyasha9** [comment]
yes

**Comment by sbdeepu09** [comment]
I have created a website template, can i contribute that

**Comment by waridrox** [comment]
I made a blog website but it doesn't use any javascript. Can I still contribute ?

**Comment by adyasha9** [comment]
@sbdeepu09 @waridrox yes, go ahead

**Comment by shubha028** [comment]
Can I contribute as a part of hactoberfest?

**Comment by vanya-24** [comment]
Please assign this to me! @adyasha9

**Comment by padmaja-22** [comment]
@adyasha9 Is this repo not eligible for hactoberfest PR's? Even after merging it is showing that this is an Ineligible PR

**Comment by adyasha9** [comment]
@padmaja-22  hold up let me look into it

**Comment by MonarthS** [comment]
@adyasha9 You have to add the "**hacktoberfest**" topic to the repository to participate.

**Comment by padmaja-22** [comment]
> @adyasha9 You have to add the "**hacktoberfest**" topic to the repository to participate.

yes

**Comment by adyasha9** [comment]
i did

**Comment by adyasha9** [comment]
@padmaja-22  I did

**Comment by adyasha9** [comment]
@vanya-24 @shubha028 I did the required changes now you can go ahead and do it

**Comment by adyasha9** [comment]
@MonarthS @padmaja-22  Thank you, guys!

**Comment by ADHIL-MOHAMMED-P-N** [comment]
@adyasha9 Done,added a frontend website

**Comment by r2codes** [comment]
please assign it to me @adyasha9 . I would like to add my cool original frontend website

**Comment by pccoder-2000** [comment]
can i add my frontend website?

**Comment by aritrochakraborty29** [comment]
I have made some cool Frontend website.. 
can you please assign me??

**Comment by adyasha9** [comment]
@aritrochakraborty29 yes, go ahead

**Comment by lekandev** [comment]
Please I would like to contribute, it's for hacktoberfest 2020 right?
I have a frontend project

**Comment by adyasha9** [comment]
This issue is closed now.
