### ISSUE TITLE
upload python, javascript, c, java animations or game codes

### ISSUE THREAD

**Issue by adyasha9** [adyasha9/hacktoberfest#11]

**Comment by Shivangi-ch** [comment]
can i add a game code?

**Comment by adyasha9** [comment]
@Shivangi-ch go ahead

**Comment by aritrochakraborty29** [comment]
I want to add some games by JavaScript, Python, C , Java..
can you please assign me.?

**Comment by adyasha9** [comment]
@aritrochakraborty29  Yes

**Comment by adyasha9** [comment]
This issue is closed now
